/* The following code was generated by JFlex 1.6.1 */

/*Fantom lexical analyzer
*	Writen by mehran rafiee
*	student id =940122610025
%{
    public enum Token {

        KEYWORD,
        IDENTIFIER,
        OPERATOR,
        INTEGER,
        FLOAT,
        STRING,
        COMMENT,
        WHITESPACE,
        DELIMITER,
        SEMICOLON,
        COMMA,
        DOT,
        LT,
        GT,
        LPAREN,
        RPAREN,
        LBRACE, 
        RBRACE, 
        LBRACK, 
        RBRACK, 
        NOT,
        EQ, 
        PLUS, 
        LTEQ, 
        GTEQ, 
        NOTEQ, 
        EQEQ, 
        DEF, 
        PPLUS, 
        ERROR
    }

%}*/


import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>E:/ProgramingTraining/CompilerDesign/Fantom/fantom_lexical_analyzer.flex</tt>
 */
public class Scanner extends sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\5\1\2\1\13\1\13\1\1\22\0\1\25\1\42\1\20"+
    "\1\41\1\21\1\70\1\65\1\12\1\31\1\32\1\40\1\66\1\43"+
    "\1\6\1\14\1\37\1\7\11\4\1\64\1\44\1\26\1\63\1\30"+
    "\2\0\5\11\1\16\2\3\1\57\11\3\1\22\2\3\1\60\1\3"+
    "\1\10\2\3\1\35\1\17\1\36\1\67\1\4\1\0\1\54\1\11"+
    "\1\45\1\61\1\15\1\50\1\3\1\46\1\51\2\3\1\52\1\3"+
    "\1\56\1\47\2\3\1\24\1\53\1\23\1\55\1\60\1\62\1\10"+
    "\2\3\1\33\1\27\1\34\7\0\1\13\u1fa2\0\1\13\1\13\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\3\1\0\1\5"+
    "\1\2\1\0\2\2\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\0\1\21"+
    "\1\22\1\23\7\2\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\2\0\1\32\1\33\1\0\1\3\2\0\1\2"+
    "\1\0\2\2\3\0\1\34\1\0\2\2\1\35\1\36"+
    "\1\37\1\40\1\0\2\40\1\41\2\2\1\42\4\2"+
    "\1\43\1\44\1\45\1\46\2\0\1\3\3\2\2\0"+
    "\2\34\3\0\2\2\1\0\1\2\1\47\1\50\3\2"+
    "\1\32\1\51\1\52\1\0\1\34\3\0\3\2\1\53"+
    "\1\2\2\0\1\2\1\54\1\2\1\55\2\0\1\56"+
    "\1\57\2\0\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\u0357\0\71\0\u0390"+
    "\0\u03c9\0\71\0\71\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\71\0\71"+
    "\0\u018f\0\u0675\0\71\0\71\0\u06ae\0\u06e7\0\u0720\0\u0759"+
    "\0\u0792\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921"+
    "\0\u095a\0\u0993\0\u09cc\0\71\0\71\0\71\0\u0a05\0\u0a3e"+
    "\0\u0a77\0\71\0\71\0\u0ab0\0\u0ae9\0\162\0\u0b22\0\u0b5b"+
    "\0\u0b94\0\u0bcd\0\71\0\71\0\71\0\71\0\u0c06\0\u0c3f"+
    "\0\71\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\71\0\u0876"+
    "\0\u0921\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\162"+
    "\0\162\0\u0eeb\0\u0f24\0\u0f5d\0\162\0\162\0\162\0\u0f96"+
    "\0\u08af\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\162"+
    "\0\u1125\0\u115e\0\u1197\0\u11d0\0\162\0\u1209\0\162\0\u1242"+
    "\0\u127b\0\162\0\162\0\u12b4\0\u12ed\0\u127b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\3\1\4\1\2\1\5\1\6\2\3"+
    "\1\7\1\0\1\10\1\11\1\3\1\0\1\12\1\0"+
    "\1\13\1\3\1\14\1\2\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\2\3\1\35\1\36\1\3"+
    "\1\37\3\3\1\40\1\41\1\3\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\74\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\16\3\12\0\1\4"+
    "\2\0\1\4\4\0\1\51\1\52\1\53\31\0\1\53"+
    "\24\0\1\4\1\0\1\54\1\4\4\0\1\51\1\55"+
    "\57\0\1\4\2\0\1\4\1\56\3\0\1\51\1\52"+
    "\1\53\31\0\1\53\20\0\1\57\2\0\10\57\1\0"+
    "\55\57\4\0\1\60\2\0\1\60\5\0\1\55\56\0"+
    "\1\3\1\61\1\0\1\62\1\61\2\3\3\0\2\3"+
    "\3\0\3\3\20\0\1\63\4\3\1\64\10\3\3\0"+
    "\1\62\2\0\1\65\2\0\10\65\1\66\3\65\1\67"+
    "\1\70\1\71\47\65\3\0\2\3\2\0\3\3\3\0"+
    "\2\3\3\0\1\3\1\72\1\3\20\0\16\3\11\0"+
    "\2\3\2\0\3\3\3\0\1\73\1\3\3\0\3\3"+
    "\20\0\16\3\71\0\1\74\34\0\1\75\124\0\1\76"+
    "\44\0\1\77\1\100\30\0\1\30\1\101\1\102\66\30"+
    "\63\0\1\103\10\0\2\3\2\0\3\3\3\0\2\3"+
    "\3\0\3\3\20\0\5\3\1\104\10\3\11\0\2\3"+
    "\2\0\3\3\3\0\2\3\3\0\3\3\20\0\2\3"+
    "\1\105\13\3\11\0\2\3\2\0\3\3\3\0\2\3"+
    "\3\0\3\3\20\0\3\3\1\106\5\3\1\107\4\3"+
    "\11\0\2\3\2\0\3\3\3\0\2\3\3\0\1\3"+
    "\1\110\1\3\20\0\16\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\11\3\1\107\4\3"+
    "\11\0\2\3\2\0\3\3\3\0\2\3\3\0\3\3"+
    "\20\0\2\3\1\111\13\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\1\3\1\112\14\3"+
    "\71\0\1\113\70\0\1\114\72\0\1\115\7\0\1\4"+
    "\2\0\1\4\4\0\1\51\1\55\50\0\1\116\6\0"+
    "\1\117\1\0\1\120\1\117\56\0\1\120\6\0\1\120"+
    "\1\0\1\62\1\120\56\0\1\62\6\0\1\56\2\0"+
    "\1\56\1\0\1\56\3\0\2\56\26\0\1\56\2\0"+
    "\1\56\3\0\1\56\4\0\1\56\21\0\1\121\62\0"+
    "\1\60\2\0\1\60\5\0\1\52\1\53\31\0\1\53"+
    "\23\0\1\3\1\122\2\0\1\122\2\3\3\0\2\3"+
    "\3\0\3\3\20\0\16\3\12\0\1\120\2\0\1\120"+
    "\64\0\2\3\2\0\3\3\3\0\2\3\3\0\3\3"+
    "\20\0\1\3\1\123\14\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\6\3\1\124\7\3"+
    "\6\0\1\65\2\0\10\65\1\66\3\65\1\67\1\70"+
    "\1\125\47\65\1\66\2\0\14\66\1\126\1\127\50\66"+
    "\1\65\2\0\10\65\1\66\3\65\1\67\1\130\1\125"+
    "\47\65\1\131\2\0\10\131\1\0\4\131\1\70\1\132"+
    "\47\131\1\65\2\0\1\133\4\65\2\133\1\65\1\66"+
    "\1\65\2\133\1\67\1\70\1\125\3\133\20\65\16\133"+
    "\6\65\3\0\2\3\2\0\3\3\3\0\2\3\3\0"+
    "\2\3\1\134\20\0\16\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\1\3\1\135\1\3\20\0\16\3"+
    "\6\0\1\77\1\101\1\102\66\77\40\100\1\136\30\100"+
    "\2\0\1\102\71\0\2\3\2\0\3\3\3\0\2\3"+
    "\3\0\3\3\20\0\7\3\1\137\6\3\11\0\2\3"+
    "\2\0\3\3\3\0\2\3\3\0\2\3\1\140\20\0"+
    "\16\3\11\0\2\3\2\0\3\3\3\0\2\3\3\0"+
    "\1\3\1\141\1\3\20\0\16\3\11\0\2\3\2\0"+
    "\3\3\3\0\2\3\3\0\3\3\20\0\7\3\1\142"+
    "\6\3\11\0\2\3\2\0\3\3\3\0\2\3\3\0"+
    "\3\3\20\0\4\3\1\143\11\3\11\0\2\3\2\0"+
    "\3\3\3\0\2\3\3\0\3\3\20\0\4\3\1\144"+
    "\11\3\12\0\1\117\2\0\1\117\6\0\1\53\31\0"+
    "\1\53\24\0\1\117\2\0\1\117\64\0\1\3\1\122"+
    "\2\0\1\122\2\3\3\0\1\3\1\145\3\0\3\3"+
    "\20\0\3\3\1\145\12\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\2\3\1\146\13\3"+
    "\11\0\2\3\2\0\3\3\3\0\1\147\1\3\3\0"+
    "\3\3\20\0\16\3\6\0\1\65\2\0\1\150\4\65"+
    "\2\150\1\65\1\66\1\65\2\150\1\67\1\70\1\125"+
    "\3\150\20\65\16\150\6\65\1\66\2\0\14\66\1\126"+
    "\1\151\50\66\1\131\2\0\1\152\4\131\2\152\1\131"+
    "\1\0\1\131\2\152\1\131\1\70\1\132\3\152\20\131"+
    "\16\152\6\131\1\65\1\153\1\0\2\133\2\65\3\133"+
    "\1\65\1\66\1\65\2\133\1\67\1\70\1\125\3\133"+
    "\20\65\16\133\6\65\3\0\2\3\2\0\3\3\3\0"+
    "\2\3\3\0\3\3\1\154\17\0\16\3\11\0\2\3"+
    "\2\0\3\3\3\0\2\3\3\0\3\3\20\0\10\3"+
    "\1\155\5\3\6\0\37\100\1\102\1\136\30\100\3\0"+
    "\2\3\2\0\3\3\3\0\2\3\3\0\3\3\20\0"+
    "\6\3\1\156\7\3\11\0\2\3\2\0\3\3\3\0"+
    "\2\3\3\0\1\3\1\157\1\3\20\0\16\3\11\0"+
    "\2\3\2\0\3\3\3\0\2\3\3\0\3\3\20\0"+
    "\14\3\1\160\1\3\11\0\2\3\2\0\3\3\3\0"+
    "\2\3\3\0\3\3\20\0\5\3\1\161\10\3\6\0"+
    "\1\65\1\162\1\0\2\150\2\65\3\150\1\65\1\66"+
    "\1\65\2\150\1\67\1\70\1\125\3\150\20\65\16\150"+
    "\6\65\1\131\1\162\1\0\2\152\2\131\3\152\1\131"+
    "\1\0\1\131\2\152\1\131\1\70\1\132\3\152\20\131"+
    "\16\152\7\131\2\0\10\131\1\0\55\131\25\0\1\154"+
    "\1\163\45\0\2\3\2\0\3\3\3\0\2\3\3\0"+
    "\2\3\1\164\20\0\16\3\11\0\2\3\2\0\3\3"+
    "\3\0\2\3\3\0\3\3\20\0\6\3\1\165\7\3"+
    "\11\0\2\3\2\0\3\3\3\0\2\3\3\0\3\3"+
    "\20\0\4\3\1\166\11\3\11\0\2\3\2\0\3\3"+
    "\3\0\1\167\1\3\3\0\3\3\20\0\16\3\6\0"+
    "\1\131\2\0\10\131\1\0\4\131\1\70\1\170\47\131"+
    "\27\0\1\171\44\0\2\3\2\0\3\3\3\0\2\3"+
    "\3\0\3\3\20\0\11\3\1\172\4\3\11\0\2\3"+
    "\2\0\3\3\3\0\2\3\3\0\3\3\20\0\1\173"+
    "\15\3\6\0\1\131\2\0\1\174\4\131\2\174\1\131"+
    "\1\0\1\131\2\174\1\131\1\70\1\132\3\174\20\131"+
    "\16\174\6\131\1\171\2\0\10\171\1\0\13\171\1\175"+
    "\41\171\1\131\1\153\1\0\2\174\2\131\3\174\1\131"+
    "\1\0\1\131\2\174\1\131\1\70\1\132\3\174\20\131"+
    "\16\174\6\131\1\171\2\0\10\171\1\0\13\171\1\175"+
    "\1\176\40\171";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4902];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\0\2\1\1\0\5\1\6\11"+
    "\1\1\1\11\1\0\1\1\2\11\13\1\2\11\2\0"+
    "\2\11\1\0\1\1\2\0\1\1\1\0\2\1\3\0"+
    "\1\1\1\0\2\1\3\11\1\1\1\0\1\1\2\11"+
    "\7\1\4\11\2\0\1\11\3\1\2\0\1\11\1\1"+
    "\3\0\2\1\1\0\11\1\1\0\1\1\3\0\5\1"+
    "\2\0\4\1\2\0\2\1\2\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuilder string = new StringBuilder();

	private Symbol symbol(int type) {
		return new JavaSymbol(type, yyline+1, yycolumn+1);
	}

	private Symbol symbol(int type, Object value) {
		return new JavaSymbol(type, yyline+1, yycolumn+1, value);
	}

/*	private String token(String text,Token token) {
        return "<" + text + "-" + token + " -L : " + yyline +" - C : " + yycolumn + ">";
    }
	 */
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(EOF);
            }
            case 127: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /*ignore*/
            }
          case 48: break;
          case 2: 
            { return symbol (IDENTIFIER);
            }
          case 49: break;
          case 3: 
            { return symbol (INTEGER);
            }
          case 50: break;
          case 4: 
            { return symbol(MINUS);
            }
          case 51: break;
          case 5: 
            { return symbol(DOT);
            }
          case 52: break;
          case 6: 
            { return symbol(LT);
            }
          case 53: break;
          case 7: 
            { return symbol(OR);
            }
          case 54: break;
          case 8: 
            { return symbol(GT);
            }
          case 55: break;
          case 9: 
            { return symbol(LPAREN);
            }
          case 56: break;
          case 10: 
            { return symbol(RPAREN);
            }
          case 57: break;
          case 11: 
            { return symbol(LBRACE);
            }
          case 58: break;
          case 12: 
            { return symbol(RBRACE);
            }
          case 59: break;
          case 13: 
            { return symbol(LBRACK);
            }
          case 60: break;
          case 14: 
            { return symbol(RBRACK);
            }
          case 61: break;
          case 15: 
            { return symbol(DIV);
            }
          case 62: break;
          case 16: 
            { return symbol(MULT);
            }
          case 63: break;
          case 17: 
            { return symbol(NOT);
            }
          case 64: break;
          case 18: 
            { return symbol(COMMA);
            }
          case 65: break;
          case 19: 
            { return symbol(SEMICOLON);
            }
          case 66: break;
          case 20: 
            { return symbol(EQ);
            }
          case 67: break;
          case 21: 
            { return symbol(COLON);
            }
          case 68: break;
          case 22: 
            { return symbol(AND);
            }
          case 69: break;
          case 23: 
            { return symbol(PLUS);
            }
          case 70: break;
          case 24: 
            { return symbol(XOR);
            }
          case 71: break;
          case 25: 
            { return symbol(MOD);
            }
          case 72: break;
          case 26: 
            { return symbol (FLOAT);
            }
          case 73: break;
          case 27: 
            { return symbol(MINUSMINUS);
            }
          case 74: break;
          case 28: 
            { return symbol (STRING);
            }
          case 75: break;
          case 29: 
            { return symbol(LTEQ);
            }
          case 76: break;
          case 30: 
            { return symbol(OROR);
            }
          case 77: break;
          case 31: 
            { return symbol(GTEQ);
            }
          case 78: break;
          case 32: 
            { return symbol (COMMENT);
            }
          case 79: break;
          case 33: 
            { return symbol(NOTEQ);
            }
          case 80: break;
          case 34: 
            { return symbol(IF);
            }
          case 81: break;
          case 35: 
            { return symbol(EQEQ);
            }
          case 82: break;
          case 36: 
            { return symbol(DEF);
            }
          case 83: break;
          case 37: 
            { return symbol(ANDAND);
            }
          case 84: break;
          case 38: 
            { return symbol(PLUSPLUS);
            }
          case 85: break;
          case 39: 
            { return symbol (FOR);
            }
          case 86: break;
          case 40: 
            { return symbol(INT);
            }
          case 87: break;
          case 41: 
            { return symbol (ECHO);
            }
          case 88: break;
          case 42: 
            { return symbol(ELSE);
            }
          case 89: break;
          case 43: 
            { return symbol(VOID);
            }
          case 90: break;
          case 44: 
            { return symbol (CLASS);
            }
          case 91: break;
          case 45: 
            { return symbol(WHILE);
            }
          case 92: break;
          case 46: 
            { return symbol (RETURN);
            }
          case 93: break;
          case 47: 
            { return symbol (STATIC);
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
//          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        Parser parser = new Parser(scanner);
        parser.parse();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
