
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 34;
  public static final int GTEQ = 45;
  public static final int MULT = 8;
  public static final int LTEQ = 44;
  public static final int STR = 55;
  public static final int COMMENT = 2;
  public static final int XOR = 58;
  public static final int INTEGER = 51;
  public static final int LPAREN = 13;
  public static final int PRIVATE = 22;
  public static final int CONTINUE = 32;
  public static final int URSHIFT = 18;
  public static final int INT = 54;
  public static final int ECHO = 59;
  public static final int MINUS = 37;
  public static final int FOR = 30;
  public static final int STATIC = 23;
  public static final int RPAREN = 14;
  public static final int OROR = 57;
  public static final int AND = 46;
  public static final int NOT = 39;
  public static final int SEMICOLON = 7;
  public static final int LT = 42;
  public static final int OR = 47;
  public static final int COMMA = 9;
  public static final int CLASS = 24;
  public static final int COMP = 38;
  public static final int ANDAND = 56;
  public static final int DIV = 40;
  public static final int PLUS = 36;
  public static final int IF = 26;
  public static final int DOT = 6;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 35;
  public static final int RETURN = 33;
  public static final int error = 1;
  public static final int EQEQ = 48;
  public static final int MOD = 41;
  public static final int NUMBER = 19;
  public static final int BREAK = 31;
  public static final int VOID = 25;
  public static final int EQ = 12;
  public static final int LBRACK = 4;
  public static final int COLON = 15;
  public static final int LBRACE = 10;
  public static final int ELSE = 27;
  public static final int PROTECTED = 21;
  public static final int RBRACK = 5;
  public static final int WHILE = 29;
  public static final int FLOAT = 3;
  public static final int PUBLIC = 20;
  public static final int RBRACE = 11;
  public static final int STRING = 52;
  public static final int DEF = 50;
  public static final int LSHIFT = 16;
  public static final int GT = 43;
  public static final int DO = 28;
  public static final int NOTEQ = 49;
  public static final int RSHIFT = 17;
  public static final int IDENTIFIER = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMENT",
  "FLOAT",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "NUMBER",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "CLASS",
  "VOID",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "AND",
  "OR",
  "EQEQ",
  "NOTEQ",
  "DEF",
  "INTEGER",
  "STRING",
  "IDENTIFIER",
  "INT",
  "STR",
  "ANDAND",
  "OROR",
  "XOR",
  "ECHO"
  };
}

